"""
Generate the examples index from the examples themselves.

`examples/README.md` was a hand-written table, and for the whole 2.x line it
described three examples as working that could not construct their agent.
The table had no way to notice: its text came from a person, not from the
files. Now each row comes from the script it names — the headline from the
first line of the docstring, the keys from its ``Required env vars:`` block —
and a test holds the committed page equal to this output.

    python scripts/examples_index.py           # write
    python scripts/examples_index.py --check   # exit 1 when a page is stale

The sections are the one hand-written part. An example that belongs to none
of them, or to two, is an error rather than a row that quietly goes missing.
"""

from __future__ import annotations

import ast
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
EXAMPLES = ROOT / "examples"
INDEX = EXAMPLES / "README.md"
README = ROOT / "README.md"
START, END = "<!-- examples:start -->", "<!-- examples:end -->"

SECTIONS = [
    ("Skills",
     "A **Skill** is the atomic unit — one prompt template, one model, one result.",
     ["01", "02", "03", "04", "19", "21"]),
    ("Tools",
     "A **Tool** wraps any callable — a REST API, an MCP server, your own function.",
     ["05", "06", "07"]),
    ("Chains",
     "A **Chain** runs steps in order; each step's output flows into the next.",
     ["08", "09", "10"]),
    ("Pool",
     "A **Pool** runs one runner over many items in parallel.",
     ["11", "12"]),
    ("Agents",
     "An **Agent** runs one loop: each turn the model calls tools or answers, "
     "and `stop_when` decides when the run ends.",
     ["13", "14", "15", "22", "24"]),
    ("Pause and resume",
     "A **Chain** can park itself until a signal arrives — a person, a webhook, "
     "a cron tick — and be resumed later, in another process, from a shared "
     "store. An agent does not park: its state is the conversation.",
     ["17", "18"]),
    ("Observe and govern",
     "What happened inside a run, and who is allowed to let a risky call through.",
     ["16", "20"]),
    ("Private models",
     "The model runs on hardware you control; nothing is sent to a vendor.",
     ["23"]),
]

HEADER = """\
# Examples

<!-- Generated by scripts/examples_index.py from each example's docstring.
     Edit the example, then run the script; tests/test_examples_index.py
     fails when this page and the scripts disagree. -->

One concept per file. Every file is self-contained: set the keys it names and
run it.

```bash
python examples/01_skill.py
```
"""

QUICK_REFERENCE = """\
## Quick reference

```python
from yait_aichain import Agent, Chain, Model, Pool, Skill
from yait_aichain.agent import step_count
from yait_aichain.pool import DONE, FAILED
from yait_aichain.state import FileStore, SuspendedResult
from yait_aichain.tools import Wait

# Skill — one prompt, one model
skill = Skill(model=Model("claude-sonnet-4-6"), prompt="Summarise: {text}")
result = skill.run(variables={"text": "..."})

# Chain — sequential steps
chain = Chain(steps=[skill_a, skill_b])
result = chain.run(variables={"topic": "..."})
print(chain.history)          # one record per step

# Pool — parallel execution
pool = Pool(skill, items=[{"text": t} for t in texts], max_flows=10)
results = pool.run()
print(pool.status)            # {PENDING: 0, RUNNING: 0, DONE: 5, FAILED: 0}

# Agent — one loop, tools or an answer each turn
agent = Agent(Model("claude-sonnet-4-6"), tools=[...], stop_when=[step_count(10)])
result = agent.run("Research the top 3 vector databases.")
print(result.output, result.stopped_by, result.tokens_used)

# Pause / resume — a chain parks until an external signal arrives
chain = Chain(steps=[draft, Wait(reason="approve?"), send], store=FileStore("runs/"))
result = chain.run(variables={"complaint": "..."})
if isinstance(result, SuspendedResult):
    # ...later, possibly in another process sharing the same store...
    chain.resume(result.run_id, signal={"reply": "approved text"})
```
"""


class IndexError_(ValueError):
    pass


def _docstring(path: Path) -> str:
    doc = ast.get_docstring(ast.parse(path.read_text()))
    if not doc:
        raise IndexError_(f"{path.name}: no module docstring")
    return doc


def headline(path: Path) -> str:
    """The first docstring line without its file-name prefix."""
    first = _docstring(path).strip().splitlines()[0].strip()
    return re.sub(r"^(\d+_\w+\.py\s+—|\d+\s+·)\s*", "", first)


def keys(path: Path) -> str:
    """What the `Required env vars:` block says, as a table cell."""
    lines = _docstring(path).splitlines()
    for i, line in enumerate(lines):
        if line.strip().startswith("Required env vars"):
            block = []
            for nxt in lines[i + 1:]:
                if not nxt.strip():
                    break
                block.append(nxt.strip())
            text = " ".join(block)
            names = re.findall(r"\b[A-Z][A-Z0-9_]*_(?:KEY|TOKEN)\b", text)
            if names:
                prefix = "any one of " if text.startswith("any one of") else ""
                return prefix + " ".join(f"`{n}`" for n in names)
            return f"*{text}*" if text else "*(none)*"
    raise IndexError_(f"{path.name}: no 'Required env vars:' block in the docstring")


def _assign() -> dict:
    files = sorted(p for p in EXAMPLES.glob("*.py"))
    placed: dict[str, list] = {}
    for title, _, numbers in SECTIONS:
        for number in numbers:
            match = [p for p in files if p.name.startswith(number + "_")]
            if len(match) != 1:
                raise IndexError_(f"section {title!r}: {number} matches "
                                  f"{[p.name for p in match]}")
            placed.setdefault(match[0].name, []).append(title)
    problems = [f"{p.name}: in no section" for p in files if p.name not in placed]
    problems += [f"{n}: in {len(t)} sections" for n, t in placed.items() if len(t) > 1]
    if problems:
        raise IndexError_("; ".join(problems))
    return {p.name: p for p in files}


def render_index() -> str:
    files = _assign()
    out = [HEADER]
    for title, intro, numbers in SECTIONS:
        out += ["---", "", f"## {title}", "", intro, "",
                "| File | What it shows | Keys |", "|---|---|---|"]
        for number in numbers:
            path = next(p for n, p in files.items() if n.startswith(number + "_"))
            out.append(f"| [`{path.name}`]({path.name}) | {headline(path)} | {keys(path)} |")
        out.append("")
    out += ["---", "", QUICK_REFERENCE]
    return "\n".join(out)


def render_readme_table() -> str:
    rows = ["| # | File | What it shows |", "|---|---|---|"]
    for name, path in _assign().items():
        rows.append(f"| {name[:2]} | [`{name}`](examples/{name}) | {headline(path)} |")
    return "\n".join(rows)


def render_readme(text: str) -> str:
    if START not in text or END not in text:
        raise IndexError_(f"README.md: markers {START} / {END} not found")
    head, rest = text.split(START, 1)
    _, tail = rest.split(END, 1)
    return f"{head}{START}\n{render_readme_table()}\n{END}{tail}"


def targets() -> dict:
    return {INDEX: render_index(), README: render_readme(README.read_text())}


def main(argv: list) -> int:
    stale = [path for path, text in targets().items() if path.read_text() != text]
    if "--check" in argv:
        for path in stale:
            print(f"stale: {path.relative_to(ROOT)} — run scripts/examples_index.py")
        return 1 if stale else 0
    for path, text in targets().items():
        path.write_text(text)
    print(f"wrote {len(targets())} page(s); {len(stale)} changed")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
